import { createContext } from "react"
import { Event, hydrateClientStorage } from "/utils/state.js"

export const initialState = {"date": "2023-11-21", "day_clean": "Tuesday November 21, 2023", "db_getUsers": null, "is_hydrated": false, "len_usuarios": 0, "link_match": "https://www.balldontlie.io/api/v1/games?dates[]=2023-11-21", "lista_partidos_perDay": [{"id": 3277479, "date": "2023-11-21T00:00:00.000Z", "home_team": {"id": 22, "abbreviation": "ORL", "city": "Orlando", "conference": "East", "division": "Southeast", "full_name": "Orlando Magic", "name": "Magic"}, "home_team_score": 0, "period": 0, "postseason": false, "season": 2023, "status": "2023-11-22T00:00:00Z", "time": null, "visitor_team": {"id": 28, "abbreviation": "TOR", "city": "Toronto", "conference": "East", "division": "Atlantic", "full_name": "Toronto Raptors", "name": "Raptors"}, "visitor_team_score": 0}, {"id": 3277480, "date": "2023-11-21T00:00:00.000Z", "home_team": {"id": 1, "abbreviation": "ATL", "city": "Atlanta", "conference": "East", "division": "Southeast", "full_name": "Atlanta Hawks", "name": "Hawks"}, "home_team_score": 0, "period": 0, "postseason": false, "season": 2023, "status": "2023-11-22T00:30:00Z", "time": null, "visitor_team": {"id": 12, "abbreviation": "IND", "city": "Indiana", "conference": "East", "division": "Central", "full_name": "Indiana Pacers", "name": "Pacers"}, "visitor_team_score": 0}, {"id": 3277481, "date": "2023-11-21T00:00:00.000Z", "home_team": {"id": 23, "abbreviation": "PHI", "city": "Philadelphia", "conference": "East", "division": "Atlantic", "full_name": "Philadelphia 76ers", "name": "76ers"}, "home_team_score": 0, "period": 0, "postseason": false, "season": 2023, "status": "2023-11-22T00:30:00Z", "time": null, "visitor_team": {"id": 6, "abbreviation": "CLE", "city": "Cleveland", "conference": "East", "division": "Central", "full_name": "Cleveland Cavaliers", "name": "Cavaliers"}, "visitor_team_score": 0}, {"id": 3277482, "date": "2023-11-21T00:00:00.000Z", "home_team": {"id": 24, "abbreviation": "PHX", "city": "Phoenix", "conference": "West", "division": "Pacific", "full_name": "Phoenix Suns", "name": "Suns"}, "home_team_score": 0, "period": 0, "postseason": false, "season": 2023, "status": "2023-11-22T02:00:00Z", "time": null, "visitor_team": {"id": 25, "abbreviation": "POR", "city": "Portland", "conference": "West", "division": "Northwest", "full_name": "Portland Trail Blazers", "name": "Trail Blazers"}, "visitor_team_score": 0}, {"id": 3277483, "date": "2023-11-21T00:00:00.000Z", "home_team": {"id": 14, "abbreviation": "LAL", "city": "Los Angeles", "conference": "West", "division": "Pacific", "full_name": "Los Angeles Lakers", "name": "Lakers"}, "home_team_score": 0, "period": 0, "postseason": false, "season": 2023, "status": "2023-11-22T03:00:00Z", "time": null, "visitor_team": {"id": 29, "abbreviation": "UTA", "city": "Utah", "conference": "West", "division": "Northwest", "full_name": "Utah Jazz", "name": "Jazz"}, "visitor_team_score": 0}], "show_right": false, "users": []}
export const StateContext = createContext(null);
export const EventLoopContext = createContext(null);
export const clientStorage = {"cookies": {}, "local_storage": {}}
export const initialEvents = [
    Event('state.hydrate', hydrateClientStorage(clientStorage)),
]